service: serverless-express-boilerplate
frameWorkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  environment:
    NODE_ENV: ${self:provider.stage}

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /{any+}
          method: ANY
